# Generated by Django 5.2.12 on 2026-04-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], default='perdido', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('outro', 'Outro')], max_length=50)),
                ('mais_de_uma_cor', models.BooleanField(default=False)),
                ('cores', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets_fotos/')),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]

# Generated by Django 5.2.12 on 2026-04-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], default='perdido', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('outro', 'Outro')], max_length=50)),
                ('mais_de_uma_cor', models.BooleanField(default=False)),
                ('cores', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets_fotos/')),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
