# Generated by Django 5.2.12 on 2026-04-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
